---

- name: inspec exec
  delegate_to: localhost
  changed_when: false
  command: >
    inspec exec {{ inspec_profile_dir }}
      -b winrm
      --host {{ inventory_hostname }}
      --user {{ ansible_user_id }}
      --password {{ ansible_password }}
      {{ inspec_attr_arg }}
  no_log: true
  ignore_errors: yes
  register: inspec_out

- name: inspec exec - stdout
  debug:
    msg: "{{ inspec_out.stdout_lines|replace(ansible_password, '<redacted>') }}"
  when: inspec_out.rc == 0 or inspec_out.rc == 101

- name: inspec exec debug - stderr
  debug:
    msg: "{{ inspec_out.stderr_lines|replace(ansible_password, '<redacted>') }}"
  when: inspec_out.rc != 0 and inspec_out.rc != 101
  failed_when: true
